
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/raminpz/config-service.git
          search-paths: /
  application:
    name: config-server
